Avoid passing number to updateOrRetrieve in array-of helper
pzuraq/ember-argument-types pull request #13
Opened 2020-12-03 18:51 UTC by Kuan-Ying

The current `arrayOf`  helper passing updates the path with `context(i)` in each iteration. This causes a trouble when `i` is 0 because `updateOrRetrieve` will directly returns the string path instead of returning a updating function, and this breaks any usage when `arrayOf` is combined with other validators.

Fix this issue by stringnify the index and add test cases for array of objects and nested arrays.

2020-12-03 20:23 UTC, km-smith requested changes

2020-12-03 20:23 UTC, km-smith commented on addon/-private/validators.js
> +      const error = ensureValidator(validator)(values[i], nextContext(`{${i}}`));
Why did we add the curly brackets around "i" here? Other than that this change seems good.

2020-12-03 21:26 UTC, Kuan-Ying commented on addon/-private/validators.js
> +      const error = ensureValidator(validator)(values[i], nextContext(`{${i}}`));
I was thinking `array.0` looks a bit weird but i don't have a strong preference of changing it. Will change it back to it was previously.

2020-12-04 00:15 UTC, jwlawrence approved these changes
lgtm, thanks for the fix!

2020-12-04 18:01 UTC, km-smith approved these changes

2020-12-04 18:01 UTC, merged